CREATE TABLE Film (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Titel TEXT NOT NULL,
	Beschreibung TEXT NOT NULL,
	Genre TEXT NOT NULL,
	Trailer TEXT NOT NULL,
	FSK INTEGER NOT NULL DEFAULT 12,
	Dauer INTEGER NOT NULL DEFAULT 90,
	Coverpfad TEXT DEFAULT NULL,
	Videopfad TEXT DEFAULT NULL
);


CREATE TABLE Vorstellung (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	FilmID INTEGER NOT NULL,
	Datum TEXT NOT NULL,
	Uhrzeit TEXT NOT NULL,
	CONSTRAINT fk_Vorstellung1 FOREIGN KEY (FilmID) REFERENCES Film(ID)
);

CREATE TABLE Ticket (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	VorstellungsID INTEGER NOT NULL,
	Code TEXT NOT NULL,
	Verfügbar INTEGER NOT NULL DEFAULT 1,
	CONSTRAINT fk_Vorstellung1 FOREIGN KEY (VorstellungsID) REFERENCES Vorstellung(ID)
);