CREATE TABLE Film (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Titel TEXT NOT NULL,
	Beschreibung TEXT NOT NULL,
	Genre TEXT NOT NULL,
	Trailer TEXT NOT NULL,
	FSK INTEGER NOT NULL DEFAULT 12,
	Dauer INTEGER NOT NULL DEFAULT 90,
	Coverpfad TEXT DEFAULT NULL,
	Videopfad TEXT DEFAULT NULL
);


CREATE TABLE Vorstellung (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	FilmID INTEGER NOT NULL,
	Datum TEXT NOT NULL,
	Uhrzeit TEXT NOT NULL,
	CONSTRAINT fk_Vorstellung1 FOREIGN KEY (FilmID) REFERENCES Film(ID)
);

CREATE TABLE Ticket (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	VorstellungsID INTEGER NOT NULL,
	Code TEXT NOT NULL,
	BenutzerID INTEGER NOT NULL,
	Preis REAL NOT NULL,
	CONSTRAINT fk_Vorstellung1 FOREIGN KEY (VorstellungsID) REFERENCES Vorstellung(ID),
	CONSTRAINT fk_Benutzer1 FOREIGN KEY (BenutzerID) REFERENCES Benutzer(ID)
);

CREATE TABLE Benutzer (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Vorname TEXT NOT NULL,
	Email TEXT NOT NULL,
	Bezahlmöglichkeit TEXT NOT NULL,
	Kreditkartennummer INTEGER,
	CVS INTEGER,
	Lieferadresse TEXT
);

CREATE TABLE SnackTyp (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Preis REAL NOT NULL,
	Beschreibung TEXT NOT NULL,
	Bildpfad TEXT NOT NULL,
);

CREATE TABLE Snack (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	SnackTypID INTEGER NOT NULL,
	BenutzerID INTEGER NOT NULL,
	Menge INTEGER NOT NULL,
	CONSTRAINT fk_Benutzer1 FOREIGN KEY (BenutzerID) REFERENCES Benutzer(ID)
	CONSTRAINT fk_SnackTyp1 FOREIGN KEY (SnackTypID) REFERENCES SnackTyp(ID)
);