# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: npm ci Node.js ${{ matrix.node-version }}
      working-directory: ./Coding/Backend
    
      run: npm ci
    - name: npm test Node.js ${{ matrix.node-version }}
      working-directory: ./Coding/Backend
    
      run: npm test

